### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List
- [x] create html/css starter files
- [x] add green and f1 svg to the html
- [x] make green background position relative and f1 svg position absolute, so f1 appears above green
- [x] fix all issues
