### ISSUE TITLE
User can accelerate and decelerate.

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/driving-game#11]
## 💰 Motivation

The user can change speed of car from normal speed to fast speed.

## 📐 Plan

When user clicks same arrow key again, car changes to fast speed.

## ✅ Task List

- [ ] keep track of number of times same arrow key is clicked
- [ ] if arrow key is clicked 2 or more times, increase speed from 4 to 8 pixels/ 16 ms
- [ ] check for bugs
