### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List
- [x] create direction array of directions
- [x] add event listener for 'keydown'
- [x] create function to change the direction of the car
- [x] apply CSS for changes to be made
- [x] add class changes to change direction of car
- [x] fix bugs/ formatting
