### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add location to data model
- [x] Make positioning absolute
- [x] Add functionality for when user presses space
- [x] Change position of car using style property to change top and left box offset styles
- [x] Have car move every 16 milliseconds using setInterval
- [x] Fix errors
