### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] add Boolean to data object
- [x] get the opposite value of the Boolean once someone clicks Space, so that the car will start moving when it turns true and the car will stop moving when it turns false
- [x] clear previous Interval
- [x] fix bugs
