### ISSUE TITLE
User can steer their car.

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] add to function to check which direction car is facing
- [x] change locationX or locationY depending on direction car should be moving
- [x] check for bugs
